[package]
name = "s-macro"
version = "0.1.0"
authors = ["ethan"]
keywords = ["string", "easy", "proc_macro", "procmacro"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "1"
proc-macro2 = "1.0"
syn = "1.0"
